### ISSUE TITLE
Change the data parameter of encrypt_data from &str to &[u8]

### ISSUE THREAD

**Issue by Istvan91** [MikhailMS/rust-radius#4]
While it is recommended to use ascii as the password, this is "only" a recommendation. Furthemore encryption is not only used by the standard Attribute "User-Password", but by some Vendor Specific Attributes.

To make the encrypt utility function more versatile it would be great to change the &str parameter to &[u8] (which would be a breaking change imho).

The enforcement of ascii/non-ascii should be done at a higher application level.

**Comment by MikhailMS** [comment]
Sounds like a great thing to resolve, thank you for pointing that out (didn't know that some vendor specific attr also using encryption)

Would review it asap :)

**Comment by MikhailMS** [comment]
It is done on dev locally, so should be bundled into next release (0.4.0, since we got a breaking(in a way) change)
