### ISSUE TITLE
Missing documentation to run client tests

### ISSUE THREAD

**Issue by Istvan91** [MikhailMS/rust-radius#5]
The `tests` folder only includes tests for a client. These seem to require a server. Please add a short description how to set up the server for testing.

(On a similar note: A short description on how the server/client for the benchmark was set up, would be nice)

**Comment by MikhailMS** [comment]
@Istvan91 
1. Pretty sure https://github.com/MikhailMS/rust-radius#tests outlines the steps to run tests :) 
One can use server implementation from **example/** directory
If there is a need to use different server, like freeradius, this is something I don't know how to setup, unfortunately
2. Benchmarks are inside **benches/** and run against server implementations from **examples/**. 


Sort of that all I can add to README, unless you believe something else is missing (or I got your issue wrong)

**Comment by MikhailMS** [comment]
Closed by 67771da

Fill free to reopen if something is still missing
